version: '3.3'

services:
  server:
    image: monitormc:latest
    restart: always
    networks:
      monitoring:
    volumes:
      - ./plugins/:/plugins
    ports:
      - 25565:25565
      - 8080:8080
      - 8123:8123

  prometheus:
    image: prom/prometheus
    restart: always
    networks:
      monitoring:
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  
  grafana:
    image: grafana/grafana:latest
    restart: always
    networks:
      monitoring:
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  
networks:
  monitoring:
    driver: bridge