version: '3.3'

services:
  server:
    image: openjdk:17
    restart: always
    networks:
      monitoring:
    volumes:
      - ./server-files/server.jar:/setup/server.jar
      - ./server-files/start.sh:/setup/start.sh
      - ./plugins/:/plugins
    ports:
      - 25565:25565
      - 8080:8080
    command: /setup/start.sh

  prometheus:
    image: prom/prometheus
    networks:
      monitoring:
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  
networks:
  monitoring:
    driver: bridge