version: '3.3'

services:
  server:
    image: openjdk:17
    restart: always
    volumes:
      - ./server-files/:/minecraft/server-files
    ports:
      - 25565:25565
    command: /minecraft/server-files/start.sh
  