version: '3.3'

services:
  server:
    image: openjdk:17
    restart: always
    volumes:
      - ./server-files/:/minecraft/server-files
      - ./plugin/:/minecraft/server-files/plugin
    ports:
      - 25565:25565
      - 8080:8080
    command: /minecraft/server-files/start.sh

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  