version: '3'

services:
  minecraft-server:
    image: openjdk:8-jdk
    volumes:
      - ./server.jar:/minecraft/server.jar
    ports:
      - 25565:25565
    command: java -Xms2G -Xmx4G -jar /minecraft/server.jar